const getFontOptions = (isPremium) => [
  // Free Tier Fonts (20 Fonts)
  { value: "Arial", label: "Arial", premium: false },
  { value: "Roboto", label: "Roboto", premium: false },
  { value: "Open Sans", label: "Open Sans", premium: false },
  { value: "Times New Roman", label: "Times New Roman", premium: false },
  { value: "Georgia", label: "Georgia", premium: false },
  { value: "Lora", label: "Lora", premium: false },
  { value: "Montserrat", label: "Montserrat", premium: false },
  { value: "Poppins", label: "Poppins", premium: false },
  { value: "Courier New", label: "Courier New", premium: false },
  { value: "Inconsolata", label: "Inconsolata", premium: false },
  { value: "Raleway", label: "Raleway", premium: false },
  { value: "Noto Sans", label: "Noto Sans", premium: false },
  { value: "Hind", label: "Hind", premium: false },
  { value: "Caveat", label: "Caveat", premium: false },
  { value: "Dancing Script", label: "Dancing Script", premium: false },
  { value: "Ubuntu", label: "Ubuntu", premium: false },
  { value: "Merriweather", label: "Merriweather", premium: false },
  { value: "PT Sans", label: "PT Sans", premium: false },
  { value: "Oswald", label: "Oswald", premium: false },
  { value: "Noto Serif", label: "Noto Serif", premium: false },

  // Premium Tier Fonts (180 Fonts)
  { value: "Proxima Nova", label: "Proxima Nova (Premium)", premium: true },
  { value: "Avenir", label: "Avenir (Premium)", premium: true },
  { value: "Gotham", label: "Gotham (Premium)", premium: true },
  { value: "Helvetica Neue", label: "Helvetica Neue (Premium)", premium: true },
  { value: "Futura", label: "Futura (Premium)", premium: true },
  { value: "Garamond", label: "Garamond (Premium)", premium: true },
  { value: "Caslon", label: "Caslon (Premium)", premium: true },
  { value: "Minion", label: "Minion (Premium)", premium: true },
  { value: "Baskerville", label: "Baskerville (Premium)", premium: true },
  { value: "Adobe Garamond", label: "Adobe Garamond (Premium)", premium: true },
  { value: "Lobster", label: "Lobster (Premium)", premium: true },
  { value: "Pacifico", label: "Pacifico (Premium)", premium: true },
  { value: "Indie Flower", label: "Indie Flower (Premium)", premium: true },
  { value: "Shadows Into Light", label: "Shadows Into Light (Premium)", premium: true },
  { value: "Great Vibes", label: "Great Vibes (Premium)", premium: true },
  { value: "Sacramento", label: "Sacramento (Premium)", premium: true },
  { value: "Courgette", label: "Courgette (Premium)", premium: true },
  { value: "Satisfy", label: "Satisfy (Premium)", premium: true },
  { value: "Anton", label: "Anton (Premium)", premium: true },
  { value: "Bebas Neue", label: "Bebas Neue (Premium)", premium: true },
  { value: "Roboto Slab", label: "Roboto Slab (Premium)", premium: true },
  { value: "Playfair Display", label: "Playfair Display (Premium)", premium: true },
  { value: "Source Sans Pro", label: "Source Sans Pro (Premium)", premium: true },
  { value: "Lato", label: "Lato (Premium)", premium: true },
  { value: "Cabin", label: "Cabin (Premium)", premium: true },
  { value: "Arimo", label: "Arimo (Premium)", premium: true },
  { value: "Fira Sans", label: "Fira Sans (Premium)", premium: true },
  { value: "Inter", label: "Inter (Premium)", premium: true },
  { value: "DM Sans", label: "DM Sans (Premium)", premium: true },
  { value: "Work Sans", label: "Work Sans (Premium)", premium: true },
  { value: "Libre Franklin", label: "Libre Franklin (Premium)", premium: true },
  { value: "Rubik", label: "Rubik (Premium)", premium: true },
  { value: "Karla", label: "Karla (Premium)", premium: true },
  { value: "Manrope", label: "Manrope (Premium)", premium: true },
  { value: "JetBrains Mono", label: "JetBrains Mono (Premium)", premium: true },
  { value: "Fira Code", label: "Fira Code (Premium)", premium: true },
  { value: "Tinos", label: "Tinos (Premium)", premium: true },
  { value: "DM Serif Text", label: "DM Serif Text (Premium)", premium: true },
  { value: "EB Garamond", label: "EB Garamond (Premium)", premium: true },
  { value: "Noto Sans Devanagari", label: "Noto Sans Devanagari (Premium)", premium: true },
  { value: "Noto Serif Devanagari", label: "Noto Serif Devanagari (Premium)", premium: true },
  { value: "Noto Sans Arabic", label: "Noto Sans Arabic (Premium)", premium: true },
  { value: "Noto Sans Hebrew", label: "Noto Sans Hebrew (Premium)", premium: true },
  { value: "Noto Sans Thai", label: "Noto Sans Thai (Premium)", premium: true },
  { value: "Noto Sans CJK JP", label: "Noto Sans CJK JP (Premium)", premium: true },
  { value: "Noto Serif CJK SC", label: "Noto Serif CJK SC (Premium)", premium: true },
  { value: "Noto Serif Thai", label: "Noto Serif Thai (Premium)", premium: true },
  { value: "Amatic SC", label: "Amatic SC (Premium)", premium: true },
  { value: "Kalam", label: "Kalam (Premium)", premium: true },
  { value: "Patrick Hand", label: "Patrick Hand (Premium)", premium: true },
  { value: "Amiri", label: "Amiri (Premium)", premium: true },
  { value: "Overpass", label: "Overpass (Premium)", premium: true },
  { value: "Barlow", label: "Barlow (Premium)", premium: true },
  { value: "Nunito Sans", label: "Nunito Sans (Premium)", premium: true },
  { value: "Alegreya", label: "Alegreya (Premium)", premium: true },
  { value: "Alegreya Sans", label: "Alegreya Sans (Premium)", premium: true },
  { value: "Source Serif Pro", label: "Source Serif Pro (Premium)", premium: true },
  { value: "PT Serif", label: "PT Serif (Premium)", premium: true },
  { value: "Cardo", label: "Cardo (Premium)", premium: true },
  { value: "Chivo", label: "Chivo (Premium)", premium: true },
  { value: "Neuton", label: "Neuton (Premium)", premium: true },
  { value: "Spectral", label: "Spectral (Premium)", premium: true },
  { value: "IBM Plex Sans", label: "IBM Plex Sans (Premium)", premium: true },
  { value: "IBM Plex Serif", label: "IBM Plex Serif (Premium)", premium: true },
  { value: "Quicksand", label: "Quicksand (Premium)", premium: true },
  { value: "Josefin Sans", label: "Josefin Sans (Premium)", premium: true },
  { value: "Josefin Slab", label: "Josefin Slab (Premium)", premium: true },
  { value: "Arvo", label: "Arvo (Premium)", premium: true },
  { value: "B612 Mono", label: "B612 Mono (Premium)", premium: true },
  { value: "Bellefair", label: "Bellefair (Premium)", premium: true },
  { value: "Fauna One", label: "Fauna One (Premium)", premium: true },
  { value: "Galindo", label: "Galindo (Premium)", premium: true },
  { value: "Jost", label: "Jost (Premium)", premium: true },
  { value: "Newsreader", label: "Newsreader (Premium)", premium: true },
  { value: "Old Standard TT", label: "Old Standard TT (Premium)", premium: true },
  { value: "Oxygen", label: "Oxygen (Premium)", premium: true },
  { value: "Quattrocento", label: "Quattrocento (Premium)", premium: true },
  { value: "Quattrocento Sans", label: "Quattrocento Sans (Premium)", premium: true },
  { value: "Red Hat Text", label: "Red Hat Text (Premium)", premium: true },
  { value: "Red Hat Display", label: "Red Hat Display (Premium)", premium: true },
  { value: "Rosario", label: "Rosario (Premium)", premium: true },
  { value: "Rosarivo", label: "Rosarivo (Premium)", premium: true },
  { value: "Saira", label: "Saira (Premium)", premium: true },
  { value: "Saira Condensed", label: "Saira Condensed (Premium)", premium: true },
  { value: "Saira Extra Condensed", label: "Saira Extra Condensed (Premium)", premium: true },
  { value: "Sansita", label: "Sansita (Premium)", premium: true },
  { value: "Slabo 27px", label: "Slabo 27px (Premium)", premium: true },
  { value: "Slabo 13px", label: "Slabo 13px (Premium)", premium: true },
  { value: "Teko", label: "Teko (Premium)", premium: true },
  { value: "Titillium Web", label: "Titillium Web (Premium)", premium: true },
  { value: "Varela Round", label: "Varela Round (Premium)", premium: true },
  { value: "Vollkorn", label: "Vollkorn (Premium)", premium: true },
  { value: "Yanone Kaffeesatz", label: "Yanone Kaffeesatz (Premium)", premium: true },
  { value: "Zilla Slab", label: "Zilla Slab (Premium)", premium: true },
  { value: "Nunito", label: "Nunito (Premium)", premium: true },
  { value: "DM Mono", label: "DM Mono (Premium)", premium: true },
  { value: "Space Mono", label: "Space Mono (Premium)", premium: true },
  { value: "Comfortaa", label: "Comfortaa (Premium)", premium: true },
  { value: "Mulish", label: "Mulish (Premium)", premium: true },
  { value: "Exo 2", label: "Exo 2 (Premium)", premium: true },
  { value: "Gudea", label: "Gudea (Premium)", premium: true },
  { value: "Maven Pro", label: "Maven Pro (Premium)", premium: true },
  { value: "Mukta", label: "Mukta (Premium)", premium: true },
  { value: "Prompt", label: "Prompt (Premium)", premium: true },
  { value: "Ropa Sans", label: "Ropa Sans (Premium)", premium: true },
  { value: "Lexend", label: "Lexend (Premium)", premium: true },
  { value: "Arapey", label: "Arapey (Premium)", premium: true },
  { value: "Libre Baskerville", label: "Libre Baskerville (Premium)", premium: true },
  { value: "Baloo 2", label: "Baloo 2 (Premium)", premium: true },
  { value: "Tiro Devanagari Hindi", label: "Tiro Devanagari Hindi (Premium)", premium: true },
  { value: "Hind Siliguri", label: "Hind Siliguri (Premium)", premium: true },
  { value: "Hind Guntur", label: "Hind Guntur (Premium)", premium: true },
  { value: "Hind Madurai", label: "Hind Madurai (Premium)", premium: true },
  { value: "Hind Kochi", label: "Hind Kochi (Premium)", premium: true },
  { value: "Karma", label: "Karma (Premium)", premium: true },
  { value: "Rajdhani", label: "Rajdhani (Premium)", premium: true },
  { value: "Yantramanav", label: "Yantramanav (Premium)", premium: true },
  { value: "Modak", label: "Modak (Premium)", premium: true },
  { value: "Glegoo", label: "Glegoo (Premium)", premium: true },
  { value: "Martel", label: "Martel (Premium)", premium: true },
  { value: "Martel Sans", label: "Martel Sans (Premium)", premium: true },
  { value: "Palanquin", label: "Palanquin (Premium)", premium: true },
  { value: "Palanquin Dark", label: "Palanquin Dark (Premium)", premium: true },
  { value: "Sura", label: "Sura (Premium)", premium: true },
  { value: "Architects Daughter", label: "Architects Daughter (Premium)", premium: true },
  { value: "Baskervville", label: "Baskervville (Premium)", premium: true },
  { value: "Domine", label: "Domine (Premium)", premium: true },
  { value: "Crimson Text", label: "Crimson Text (Premium)", premium: true },
  { value: "Merriweather Sans", label: "Merriweather Sans (Premium)", premium: true },
  { value: "Open Sans Condensed", label: "Open Sans Condensed (Premium)", premium: true },
  { value: "Bitter", label: "Bitter (Premium)", premium: true },
  { value: "Droid Sans", label: "Droid Sans (Premium)", premium: true },
  { value: "Proza Libre", label: "Proza Libre (Premium)", premium: true },
  { value: "Noto Sans CJK KR", label: "Noto Sans CJK KR (Premium)", premium: true },
  { value: "Noto Sans Tamil", label: "Noto Sans Tamil (Premium)", premium: true },
  { value: "Noto Sans Telugu", label: "Noto Sans Telugu (Premium)", premium: true },
  { value: "Noto Sans Bengali", label: "Noto Sans Bengali (Premium)", premium: true },
  { value: "Noto Sans Gujarati", label: "Noto Sans Gujarati (Premium)", premium: true },
  { value: "Noto Sans Kannada", label: "Noto Sans Kannada (Premium)", premium: true },
  { value: "Noto Sans Malayalam", label: "Noto Sans Malayalam (Premium)", premium: true },
  { value: "Noto Sans Gurmukhi", label: "Noto Sans Gurmukhi (Premium)", premium: true },
  { value: "Noto Sans Oriya", label: "Noto Sans Oriya (Premium)", premium: true },
  { value: "Noto Sans Sinhala", label: "Noto Sans Sinhala (Premium)", premium: true },
  { value: "Noto Sans Armenian", label: "Noto Sans Armenian (Premium)", premium: true },
  { value: "Noto Sans Georgian", label: "Noto Sans Georgian (Premium)", premium: true },
  { value: "Noto Sans Khmer", label: "Noto Sans Khmer (Premium)", premium: true },
  { value: "Noto Sans Lao", label: "Noto Sans Lao (Premium)", premium: true },
  { value: "Noto Sans Myanmar", label: "Noto Sans Myanmar (Premium)", premium: true },
  { value: "Noto Sans Ethiopic", label: "Noto Sans Ethiopic (Premium)", premium: true },
  { value: "Noto Sans Cherokee", label: "Noto Sans Cherokee (Premium)", premium: true },
  { value: "Noto Sans Mongolian", label: "Noto Sans Mongolian (Premium)", premium: true },
  { value: "Noto Sans Tibetan", label: "Noto Sans Tibetan (Premium)", premium: true },
  { value: "Noto Sans Yi", label: "Noto Sans Yi (Premium)", premium: true },
  { value: "Abril Fatface", label: "Abril Fatface (Premium)", premium: true },
  { value: "Alfa Slab One", label: "Alfa Slab One (Premium)", premium: true },
  { value: "Bree Serif", label: "Bree Serif (Premium)", premium: true },
  { value: "Cinzel", label: "Cinzel (Premium)", premium: true },
  { value: "Crete Round", label: "Crete Round (Premium)", premium: true },
  { value: "Fjalla One", label: "Fjalla One (Premium)", premium: true },
  { value: "Francois One", label: "Francois One (Premium)", premium: true },
  { value: "Lalezar", label: "Lalezar (Premium)", premium: true },
  { value: "Patua One", label: "Patua One (Premium)", premium: true },
  { value: "Righteous", label: "Righteous (Premium)", premium: true },
  { value: "Rokkitt", label: "Rokkitt (Premium)", premium: true },
  { value: "Vidaloka", label: "Vidaloka (Premium)", premium: true },
].filter((font) => !font.premium || (font.premium && isPremium));

export default getFontOptions;